version: '3'
services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./.config/collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
    depends_on:
      - tempo
      - loki
      - prometheus

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./tmp/loki:/loki/
      - ./.config/loki-config.yml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./.config/tempo.yaml:/etc/tempo.yaml
      - ./tmp/tempo:/tmp/tempo

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=exemplar-storage'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - ./.config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./tmp/prometheus:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./tmp/grafana/:/var/lib/grafana/
      - ./.config/grafana/dashboards:/var/lib/grafana/dashboards
      - ./.config/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./.config/grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
 


