global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9090']
  
  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']
 
  - job_name: blackbox
    static_configs:
      - targets: ['blackbox-exporter:9115']